### ISSUE TITLE
question about paths in DWT

### ISSUE THREAD

**Issue by Bruceworld0** [Y-Xiang-hub/Generate-Adversarial-Examples-By-Digital-Watermarking#2]
[Generating-Image-Adversarial-Examples-by-Embedding-Digital-Watermarks](https://github.com/Y-Xiang-hub/Generating-Image-Adversarial-Examples-by-Embedding-Digital-Watermarks)/[DWT](https://github.com/Y-Xiang-hub/Generating-Image-Adversarial-Examples-by-Embedding-Digital-Watermarks/tree/master/DWT)/Experiment_C10_DWT.py

    # DWT
    model_path = 'path-1 + .pth'
    ori_list_path = 'path-2'
    buff_img_path = 'path-3'
    wm_path = 'path-4'
    final_img_path = 'path-5'
    save_record_path = 'path-6 + .txt'

how to set the paths?

**Comment by Y-Xiang-hub** [comment]
Here is an example of the paths with the folder structure:

Example:
`model_path` = 'C:/Desktop/model/densenet121.pth'
`ori_list_path` = 'C:/Desktop/Dataset/CIFAR-10/test/0'
`buff_img_path` = 'C:/Desktop/buffer'
`wm_path =` 'C:/Desktop/Dataset/CIFAR-10/watermark/' 
`final_img_path` = 'C:/Desktop/Dataset/CIFAR-10/DWT_AEs/densenet121/0'
`save_record_path`= 'C:/Desktop/Dataset/CIFAR-10/DWT_AEs/densenet121/0/record.txt'

Folder Structure:
📂Desktop
 ┣ 📂model
 ┃ ┣ 📜densenet121.pth
 ┃ ┣ 📜googlenet.pth
 ┃ ┗ ...
 ┣ 📂Dataset
 ┃ ┣ 📂CIFAR-10
 ┃ ┃ ┣ 📂test
 ┃ ┃ ┃ ┣ 📂0 **(only images)**
 ┃ ┃ ┃ ┣ 📂1
 ┃ ┃ ┃ ┣ 📂2
 ┃ ┃ ┃ ┣ 📂3
 ┃ ┃ ┃ ┣ 📂4
 ┃ ┃ ┃ ┣ 📂5
 ┃ ┃ ┃ ┣ 📂6
 ┃ ┃ ┃ ┣ 📂7
 ┃ ┃ ┃ ┣ 📂8
 ┃ ┃ ┃ ┗ 📂9
 ┃ ┃ ┣ 📂watermark
 ┃ ┃ ┃ ┣ 📂0 **(only images)**
 ┃ ┃ ┃ ┣ 📂1
 ┃ ┃ ┃ ┣ 📂2
 ┃ ┃ ┃ ┣ 📂3
 ┃ ┃ ┃ ┣ 📂4
 ┃ ┃ ┃ ┣ 📂5
 ┃ ┃ ┃ ┣ 📂6
 ┃ ┃ ┃ ┣ 📂7
 ┃ ┃ ┃ ┣ 📂8
 ┃ ┃ ┃ ┗ 📂9
 ┃ ┃ ┣ 📂DWT_AEs
 ┃ ┃ ┃ ┣ 📂densenet121
 ┃ ┃ ┃ ┃ ┣ 📂0 **(images and a text file)**
 ┃ ┃ ┃ ┃ ┃ ┣ 📜1.jpg
 ┃ ┃ ┃ ┃ ┃ ┣ 📜2.jpg
 ┃ ┃ ┃ ┃ ┃ ┣ ...
 ┃ ┃ ┃ ┃ ┃ ┗ 📜record.txt
 ┃ ┃ ┃ ┃ ┣ 📂1
 ┃ ┃ ┃ ┃ ┣ 📂2
 ┃ ┃ ┃ ┃ ┣ 📂3
 ┃ ┃ ┃ ┃ ┣ 📂4
 ┃ ┃ ┃ ┃ ┣ 📂5
 ┃ ┃ ┃ ┃ ┣ 📂6
 ┃ ┃ ┃ ┃ ┣ 📂7
 ┃ ┃ ┃ ┃ ┣ 📂8
 ┃ ┃ ┃ ┃ ┗ 📂9
 ┃ ┃ ┃ ┣ 📂googlenet
 ┃ ┃ ┃ ┗ ...
 ┗ 📂buffer **(blank folder)**
